### ISSUE TITLE
[Bug]: Client Crash (1.20)

### ISSUE THREAD

**Issue by nvb-uy** [Toadstool-Studios/Creeper-Overhaul#78] opened 2023-06-23 20:42 UTC
### Bug Description

This crash is happening to various players in a 200 mod modpack (Prominence II)

Similar: 
https://github.com/bernie-g/geckolib/issues/446

Logs:
https://mclo.gs/g0XwhR9

### How to Reproduce?

1. Enter a world
2. Go near a creeper from the mod
3. Crash

### Version

3.0.0

### Mod Loader Version

1.20 - 0.14.21

### Mod Loader

Fabric

### Logs or additional context

https://github.com/bernie-g/geckolib/issues/446

https://mclo.gs/g0XwhR9

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment] 2023-06-25 10:22
The fix for this right now is in the client settings to turn off the replaced creeper entity.

**Comment by nvb-uy** [comment] 2023-06-25 10:23
Thanks!

**Comment by ThatGravyBoat** [comment] 2023-06-26 19:22
This is now fixed by a version working around the compatibility issue in geckolib and modernfix

**Closed as completed by ThatGravyBoat** 2023-06-26 19:22 UTC
Labels: bug

**Comment by zoqin** [comment] 2024-03-06 21:36
[1.20.1 Forge (clean install of every component)]
Creeper Overhaul + Modernfix + Thermal series crash (still/again ?)

https://mclo.gs/7cLU3G0

Old workaround still work tho

**Comment by ThatGravyBoat** [comment] 2024-03-07 02:25
Different crash thermal uses a method very unsafely, please report it to them, neoforge in future versions removed this method due to how mods were using it unsafely

**Comment by zoqin** [comment] 2024-03-07 02:55
Good to know, I will report to them ASAP

Thanks for your valuable input

**Comment by Mrthomas20121** [comment] 2024-03-07 09:38
https://github.com/CoFH/ThermalCore/blob/1.20.x/src/main/java/cofh/thermal/core/client/event/TCoreClientSetupEvents.java#L42 thermal already fixed it in dev. I don't know when King Lemming will publish the fix(fyi I do not work for team cofh)

**Comment by zoqin** [comment] 2024-03-07 09:56
At the time or writting as the fixed have not been shared and/or for future user of conflicting version

Thermal series share this work around "Disable the festive mobs in thermals client config" on their discord

Here is a link to the related post in the CoFH team discord 
https://canary.discord.com/channels/399037120930512897/762398119425736735/1204504778684502166

It can be a better workaround as it's less destructive for Creeper Overhaul and festive mobs is not a big feature to disable (in my POV)

**Comment by ThatGravyBoat** [comment] 2024-03-07 14:31
Creeper Overhaul already contains festive versions of the models so disabling COFH festive mobs will be better as even when it does come to the date of when a festive mob would happen creeper overhaul would already have a festive model

**Comment by Halilman04** [comment] 2025-04-02 20:56
I don't undestand how the problem is solved, can somebody help ?
