### ISSUE TITLE
[Bug]: Crash together with Thermal Series

### ISSUE THREAD

**Issue by pali6** [Toadstool-Studios/Creeper-Overhaul#122] opened 2024-02-25 23:07 UTC
### Bug Description

Creeper Overhaul + Thermal Series (+ dependencies) results in a crash during loading of the game. Originally this happened to me when I tried to update a larger modpack but I was able to reproduce it just in the presence of these mods. So it's likely that a recent change either to this mod or to Thermal Series caused the crash.

This happens with the latest Thermal Foundation version (11.0.2.64). Let me know if the bug is in their code instead, I will go make an issue there if that's the case. Let me know if you need any more info.

Small side issue: The Curseforge page for Creeper Overhaul seems to lack dependencies (geckolib and resourcefulconfig).

### How to Reproduce?

1. Install Creeper Overhaul 3.0.2
2. Install Thermal Foundation ([link to current latest version at the time of the report](https://www.curseforge.com/minecraft/mc-mods/thermal-foundation/files/4979840))
3. Launch Minecraft, crash

### Version

3.0.2

### Mod Loader Version

47.2.0

### Mod Loader

Forge

### Logs or additional context

Crash log: https://pastebin.com/rSFkFqzJ

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment] 2024-03-04 02:38
Duplicate of #78

**Closed as completed by ThatGravyBoat** 2024-03-04 02:38 UTC
Labels: bug
