### ISSUE TITLE
[Conflict]:

### ISSUE THREAD

**Issue by linkjankens** [Toadstool-Studios/Creeper-Overhaul#126] opened 2024-04-05 12:54 UTC
### Bug Description

There appears to be a conflict between Creeper Overhaul and Thermal Foundation, and I don't know how or why, I feel like that's a pretty random conflict. Modpack gets all the way through loading mods and crashes before getting to the main Minecraft menu.

Using
Neoforge 47.1.104
Creeper Overhaul 3.0.2
Thermal Foundation 11.0.2

### How to Reproduce?

1 make modpack of thermal foundation and creeper overhaul in neoforge
2 launch
3 crash

### Expected Behavior

It should just launch and get to the main minecraft menu

### Version

3.0.2

### Mod Loader Version

47.1.104

### Mod Loader

Forge

### Logs or additional context

https://mclo.gs/XGtkt6y

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by linkjankens** [comment] 2024-04-05 12:55
I should say, if I take out thermal it launches properly with no issues. It's not a neo/forge issue

**Comment by ThatGravyBoat** [comment] 2024-04-07 19:02
Duplicate of #78

**Closed as not planned by ThatGravyBoat** 2024-04-07 19:02 UTC
Labels: bug
